Hint to new userconfig file for ssh servers in headless setups.
raspberrypi/documentation pull request #2630
Opened 2022-09-29 05:32 UTC by gituser789

The new headless setup was introduced into the documentation.
But this hint was missing in the ssh-server section. 

A user just looking into the ssh-server part does not know about this new feature, which was introduced april 2022.

2022-09-29 08:55 UTC, aallan requested changes
We tend not to add specific dates into the documentation as this ages quickly into being irrelevant information.

2022-09-29 09:34 UTC, gituser789 commented
Updated according your hint.

2022-09-29 09:35 UTC, aallan submitted a review, later dismissed

2022-09-29 10:08 UTC, aallan commented
Automated build fails, please correct the errors and we'll look at the PR again.

```
Traceback (most recent call last):
  File "/home/runner/work/documentation/documentation/scripts/create_nav.py", line 123, in <module>
    raise Exception("{} has an internal-link to {} but that destination doesn't exist".format(filepath, linkinfo['url']))
Exception: documentation/asciidoc/computers/remote-access/secure-shell.adoc has an internal-link to computers/headless.adoc but that destination doesn't exist
```

2022-09-29 11:52 UTC, gituser789 commented
internal linking is fixed

2022-10-06 06:29 UTC, gituser789 commented
Hi,
i fixed the internal linking. Can you review the PR again?

2022-10-06 08:31 UTC, gituser789 commented
One link was changed by mistake, this was reversed.

2022-10-06 08:56 UTC, gituser789 commented
Sorry for some trouble. May it is possible to run the tests before the review?

The documentation linkin should work like
`main-adoc-file.adoc#section[name]`

I was mixing different link styles. I updated it now to
`configuration.adoc#configuring-a-user[Configuring a User]`
and the section [[configuring-a-user]] was introduced inside `headless.adoc`, what is linked in `configuration.adoc`

Please review again.

2022-10-06 09:05 UTC, aallan approved these changes

2022-10-06 09:05 UTC, merged