Add placeholder image and update instructional text
raspberrypi/documentation pull request #3119
Opened 2023-09-15 23:47 UTC by jehlers42

I made a rough placeholder image to illustrate the display's pins in the hopes of reducing confusion. If it's good enough, perfect. If not, I'll get someone to work up a better one.

I also updated the display article to remove (hopefully) the ambiguity of the original text. The new image plays a role. The warning text is cribbed from the display's product brief.

The initial comment in issue #2977 makes it seem like you could technically power the Pi using the display by plugging into the display while the GPIOs are connected with jumpers, but I didn't include that as an option because it doesn't seem like a great one (if it's even possible).

Closes issues #2977 and #3007.

2023-09-16 09:12 UTC, aallan commented
@jehlers42 Can you create an Asana task to get the placeholder image redone by Design when they get a chance. Thanks.

2023-09-16 09:21 UTC, aallan requested changes

2023-09-16 09:21 UTC, aallan commented on documentation/asciidoc/accessories/display/display_intro.adoc
> +image::images/GPIO_power-500x333.jpg[DSI Display pinout]
This image needs reshot by Brian. He has an Asana task to reshoot all (most) of the existing documentation imagery. So no need to nudge him about this one.

2023-09-16 09:21 UTC, aallan commented on documentation/asciidoc/accessories/display/display_intro.adoc
> +The following image shows how to attach a Raspberry Pi to the back of the Touch Display using the included standoffs. It also shows the connections you need to make between Raspberry Pi and the displ
I think this needs properly expanding with several images that show this process step-by-step. Possibly we should go down the route of an animated GIF, e.g. see https://www.raspberrypi.com/documentation/accessories/build-hat.html#preparing-your-build-hat.

2023-09-16 09:21 UTC, aallan commented on documentation/asciidoc/accessories/display/display_intro.adoc
> +There are two options to power the Touch Display: using the Raspberry Pi's GPIO to send power, or powering the display directly with a separate micro USB cable.
Should sub-section, if there are two options there should be two separate sections.

2023-09-16 13:49 UTC, aallan commented on documentation/asciidoc/accessories/display/display_intro.adoc
> +image::images/touch-GPIO.png[Illustration of display pins, width=250]
Don't use pixel widths, e.g. `width=250`. Instead use percentiles, e.g. `width=50%`

2023-09-16 14:08 UTC, aallan commented
It's a decent start, but was anticipating a bit more of an overhaul here. I'm not the greatest fan of FAQ-based documentation, I think it's a real failure of narrative. This page has both a "troubleshooting" and "tips and tricks" section. These really need to get integrated into the documentation proper.

One thing to bear in mind is that this page has been fairly extensively modified on the `bookworm` branch in 82d55309dc9c6365259e77b6b91ff89ec8c11d34 by @lurch. I think the best move here would be to  change the base branch you're targeting the PR against and commit onto the `bookworm` branch.

2023-09-16 14:09 UTC, aallan commented
Flipped it onto `bookworm` and it looks like there are some merge conflicts as a result.

2023-09-17 22:38 UTC, jehlers42 commented
Closing this due to messing up during conflict resolution. New PR for redone branch is #3121; comments are being taken into account.

2023-09-17 22:38 UTC, closed without merging