Update building.adoc
raspberrypi/documentation pull request #3769
Opened 2024-07-13 21:34 UTC by ehorohorin

path to broadcom/*.dtb fixed for 64-bit (6.5+), could you check and validate this?
native rpi5 build

2024-07-13 21:58 UTC, nathan-contino commented
This is in the 32-bi section, so it doesn't seem right to me that it should use `amd64`. That being said, I don't know as much about this as I'd like, so I may be missing something (maybe the Pi 5 doesn't even have an `amd` dir?) I'll close this in a day or two if I don't see any concrete evidence that it should change.

2024-07-15 08:36 UTC, nathan-contino commented
@pelwell small PR, do you know if this is correct?

2024-07-15 08:45 UTC, pelwell requested changes
@ehorohorin I think you've missed that the section you are modifying is for installing the 32-bit kernel. The 64-bit install is earlier in the document and already includes the correct path.

2024-07-15 14:51 UTC, ehorohorin commented
Sorry, my bad.

2024-07-15 14:52 UTC, ehorohorin commented
No need to apply it.

2024-07-15 14:52 UTC, closed without merging